### PR TITLE
Windows support - fixed pass helper

### PR DESCRIPTION
**Pull request by alexsaveliev**
- removed single quotes around password in pass helper, because Windows echo prints them as well

### CODE REVIEW

**Comment by keegancsmith** [comment]
LGTM

**Comment by keegancsmith** [comment]
What happens on windows if the password has two spaces in it? Will echo collapse it to one space?

**Comment by alexsaveliev** [comment]
You are right, PR does not handle situation when password ends with spaces..

**Comment by alexsaveliev** [comment]
Closing in favor of sourcegraph/go-vcs#83

**Pull request closed without merging**
